version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - API_BASE_URL=${API_BASE_URL:-http://localhost:8000}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_BASE_URL=${API_BASE_URL:-http://localhost:8000}
    volumes:
      - npm-cache:/root/.npm
    restart: unless-stopped

volumes:
  npm-cache: