version: '3'

# === 共通操作（フルスタック統合タスク） ===
tasks:
  list:
    desc: "task command lists"
    cmds:
      - task --list

  install:
    desc: "Install all dependencies and setup Git hooks"
    cmds:
      - task install:backend
      - task install:frontend
      - task install:similarity
      - task install:hooks

  dev:
    desc: "Start both frontend and backend development servers"
    deps: [dev:backend, dev:frontend]

  build:
    desc: "Build both frontend and backend"
    cmds:
      - task build:backend
      - task build:frontend

  test:
    desc: "Run all tests"
    cmds:
      - task test:backend
      - task test:frontend

  check:all:
    desc: "Run all quality checks"
    cmds:
      - task check:backend
      - task check:frontend

  fix:all:
    desc: "Run integrated auto-fix for both frontend and backend"
    cmds:
      - task fix:backend
      - task fix:frontend

  check:fix:all:
    desc: "Run check auto-fix for both frontend and backend"
    cmds:
      - task check:fix:backend
      - task check:fix:frontend

  format:fix:all:
    desc: "Run format auto-fix for both frontend and backend"
    cmds:
      - task format:fix:backend
      - task format:fix:frontend

  clean:
    desc: "Clean all generated files"
    cmds:
      - task clean:backend
      - task clean:frontend

  install:similarity:
    desc: "Install similarity-ts via mise"
    cmds:
      - mise exec -- cargo install similarity-ts

  install:hooks:
    desc: "Install Git hooks using lefthook"
    cmds:
      - |
        echo "🔧 Setting up Git hooks..."
        lefthook install
        echo "✅ Git hooks installed successfully"
        echo "ℹ️  Quality checks will now run automatically on commit and push"

  # === Docker含む共通操作 ===
  docker:build:
    desc: "Build all Docker images"
    cmds:
      - task docker:build:backend
      - task docker:build:frontend

  docker:up:
    desc: "Start all Docker environments"
    cmds:
      - task docker:up:backend
      - task docker:up:frontend

  docker:down:
    desc: "Stop all Docker environments"
    cmds:
      - task docker:down:backend
      - task docker:down:frontend

  docker:up:db:
    desc: "Start database container (auto-detect DEBUG mode)"
    cmds:
      - task -d backend docker:db:detached

  docker:logs:db:
    desc: "Show database container logs"
    cmds:
      - task -d backend docker:logs:db

  docker:restart:db:
    desc: "Restart database container"
    cmds:
      - task -d backend docker:restart:db

  # === Frontend専用操作 ===
  install:frontend:
    desc: "[Frontend] Install dependencies using Bun"
    dir: frontend
    cmds:
      - bun install

  dev:frontend:
    desc: "[Frontend] Start development server"
    dir: frontend
    cmds:
      - bun run dev

  build:frontend:
    desc: "[Frontend] Build production application"
    dir: frontend
    cmds:
      - bun run build

  test:frontend:
    desc: "[Frontend] Run tests"
    dir: frontend
    cmds:
      - bun run test

  check:frontend:
    desc: "[Frontend] Run all quality checks"
    dir: frontend
    cmds:
      - bun run check
      - bun run format
      - bun run typecheck

  fix:frontend:
    desc: "[Frontend] Run integrated auto-fix (check:fix + format:fix)"
    dir: frontend
    cmds:
      - task fix:all

  check:fix:frontend:
    desc: "[Frontend] Run Biome auto-fix (including unsafe fixes)"
    dir: frontend
    cmds:
      - task check:fix

  format:fix:frontend:
    desc: "[Frontend] Auto-format code with Biome"
    dir: frontend
    cmds:
      - task format:fix

  rebuild:frontend:
    desc: "[Frontend] Clean .next cache and rebuild Next.js application"
    dir: frontend
    cmds:
      - task rebuild

  clean:frontend:
    desc: "[Frontend] Clean generated files"
    dir: frontend
    cmds:
      - rm -rf .next node_modules/.cache dist storybook-static

  ui:add:
    desc: "[Frontend] Add shadcn/ui component"
    dir: frontend
    cmds:
      - task ui:add {{.CLI_ARGS}}

  docker:build:frontend:
    desc: "[Frontend] Build Docker image"
    dir: frontend
    cmds:
      - docker-compose -f docker/docker-compose.yml build

  docker:up:frontend:
    desc: "[Frontend] Start Docker environment"
    dir: frontend
    cmds:
      - docker-compose -f docker/docker-compose.yml up

  docker:down:frontend:
    desc: "[Frontend] Stop Docker environment"
    dir: frontend
    cmds:
      - docker-compose -f docker/docker-compose.yml down

  # === Backend専用操作 ===
  install:backend:
    desc: "[Backend] Install dependencies using uv"
    dir: backend
    cmds:
      - uv sync --group dev

  dev:backend:
    desc: "[Backend] Start development server"
    dir: backend
    cmds:
      - uv run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  build:backend:
    desc: "[Backend] Build backend (placeholder)"
    dir: backend
    cmds:
      - echo "Backend build completed"

  test:backend:
    desc: "[Backend] Run tests with pytest"
    dir: backend
    cmds:
      - uv run pytest

  check:backend:
    desc: "[Backend] Run all code quality checks"
    dir: backend
    cmds:
      - uv run ruff check .
      - uv run ruff format . --check
      - uv run mypy src

  fix:backend:
    desc: "[Backend] Auto-fix all possible issues (lint + format)"
    dir: backend
    cmds:
      - task fix:all

  check:fix:backend:
    desc: "[Backend] Run linting with ruff and auto-fix issues"
    dir: backend
    cmds:
      - task lint:fix

  format:fix:backend:
    desc: "[Backend] Format code with ruff"
    dir: backend
    cmds:
      - task format

  clean:backend:
    desc: "[Backend] Clean generated files"
    dir: backend
    cmds:
      - rm -rf .pytest_cache .mypy_cache .ruff_cache __pycache__
      - find . -name "*.pyc" -delete

  docker:build:backend:
    desc: "[Backend] Build Docker image"
    cmds:
      - task -d backend docker:build

  docker:up:backend:
    desc: "[Backend] Start Docker environment"
    cmds:
      - task -d backend docker:up

  docker:down:backend:
    desc: "[Backend] Stop Docker environment (includes database)"
    cmds:
      - task -d backend docker:down

  # マイグレーション関連
  migrate:
    desc: "[Backend] Run auto migration (generate + upgrade)"
    dir: backend
    cmds:
      - uv run python -m src.script.auto_migrate

  migrate:generate:
    desc: "[Backend] Generate migration only (no upgrade)"
    dir: backend
    cmds:
      - uv run python -m src.script.auto_migrate --no-upgrade

  migrate:status:
    desc: "[Backend] Show migration status"
    dir: backend
    cmds:
      - uv run python -m src.script.auto_migrate --status

  migrate:upgrade:
    desc: "[Backend] Upgrade database to latest migration"
    dir: backend
    cmds:
      - uv run alembic upgrade head

  migrate:downgrade:
    desc: "[Backend] Safely rollback database by one migration"
    dir: backend
    cmds:
      - uv run python -m src.script.migration_safety --downgrade

  migrate:check:
    desc: "[Backend] Check migration files integrity"
    dir: backend
    cmds:
      - uv run python -m src.script.migration_safety --check-only

  migrate:reset:
    desc: "[Backend] Reset database to base (remove all migrations)"
    dir: backend
    cmds:
      - echo "⚠️  データベースを初期状態にリセットします"
      - uv run alembic downgrade base
      - echo "✅ データベースリセット完了"

  migrate:history:
    desc: "[Backend] Show migration history"
    dir: backend
    cmds:
      - uv run alembic history