version: '3'

tasks:
  install:
    desc: Install dependencies using uv
    cmds:
      - uv sync --group dev

  dev:
    desc: Start development server
    cmds:
      - uv run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  lint:
    desc: Run linting with ruff
    cmds:
      - uv run ruff check .

  format:
    desc: Format code with ruff
    cmds:
      - uv run ruff format .

  test:
    desc: Run tests with pytest
    cmds:
      - uv run pytest

  typecheck:
    desc: Run type checking with mypy
    cmds:
      - uv run mypy src

  docker:build:
    desc: Build Docker image
    cmds:
      - docker compose -f docker/docker-compose.yml build

  docker:up:
    desc: Start Docker containers
    cmds:
      - docker compose -f docker/docker-compose.yml up

  docker:down:
    desc: Stop Docker containers
    cmds:
      - docker compose -f docker/docker-compose.yml down

  clean:
    desc: Clean up generated files
    cmds:
      - rm -rf .pytest_cache
      - rm -rf .mypy_cache
      - rm -rf .ruff_cache
      - rm -rf __pycache__
      - find . -name "*.pyc" -delete
      - find . -name "*.pyo" -delete