name: Frontend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

defaults:
  run:
    working-directory: frontend

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'  # Matches frontend/.mise.toml
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.1.8'    # Matches frontend/.mise.toml
      
      - name: Verify tool versions
        run: |
          echo "Node.js version:"
          node --version
          echo "Bun version:"
          bun --version
      
      - name: Install dependencies
        run: bun install
      
      - name: Run environment check
        run: bun run env:check
      
      - name: Run code quality checks
        run: |
          bun run check
          bun run format
          bun run typecheck
      
      - name: Build application
        run: bun run build
      
      - name: Run tests (if test files exist)
        run: bun run test || echo "No test files found, skipping tests"
        continue-on-error: true