name: Frontend Docker Build

on:
  push:
    branches: [main, develop]
    paths: ['frontend/**']
  pull_request:
    branches: [main]
    paths: ['frontend/**']

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'
      
      - name: Install dependencies
        run: |
          cd frontend
          npm install
      
      - name: Run code quality checks
        run: |
          cd frontend
          npm run check
          npm run format
          npm run typecheck
      
      - name: Build application
        run: |
          cd frontend
          npm run build
      
      - name: Build Docker image
        run: |
          cd frontend
          docker build -f docker/Dockerfile -t frontend:latest .
      
      - name: Test Docker container
        run: |
          cd frontend
          docker run -d -p 3000:3000 --name frontend-test \
            -e BACKEND_API_URL=http://localhost:8000 \
            frontend:latest
          sleep 10
          curl -f http://localhost:3000 || exit 1
          docker stop frontend-test
          docker rm frontend-test
      
      - name: Clean up
        if: always()
        run: |
          docker rmi frontend:latest || true