name: Frontend Docker Build

on:
  push:
    branches: [main, develop]
    paths: ['frontend/**']
  pull_request:
    branches: [main]
    paths: ['frontend/**']

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          version: 2024.1.0
      
      - name: Install frontend tools
        run: |
          cd frontend
          mise install
      
      - name: Install dependencies
        run: |
          cd frontend
          task install
      
      - name: Run code quality checks
        run: |
          cd frontend
          task check:all
      
      - name: Build Docker image
        run: |
          cd frontend
          task docker:build
      
      - name: Test Docker container
        run: |
          cd frontend
          task docker:run
          sleep 10
          curl -f http://localhost:3000 || exit 1
          task docker:stop
      
      - name: Clean up
        if: always()
        run: |
          cd frontend
          task docker:clean || true